repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.9.10'  # Use the latest stable tag
    hooks:
   # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format